user_access/urls.py
from django.urls import path

from user_access import views
from django.contrib.auth.views import LogoutView

app_name = 'user_access'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('login/', views.UserLoginView.as_view(), name='login'),

    path('vehiclelist', views.VehicleListView.as_view(), name='vehiclelist'),
    path('vehiclelist1', views.VehicleList1View.as_view(), name='vehiclelist1'),
    path('vehiclelist3', views.VehicleList3View.as_view(), name='vehiclelist3'),


    path('create/', views.VehicleCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.VehicleDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.VehicleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.VehicleDeleteView.as_view(), name='delete'),


    path('user-signup/', views.UserSignupView.as_view(), name='usersignup'),
    path('admin-signup/', views.AdminSignupView.as_view(), name='adminsignup'),
    path('superuser-signup/', views.SuperAdminSignupView.as_view(), name='superadminsign'),


    path('logout/', views.UserLogoutView.as_view(), name='logout'),




]

vehiclems/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('user_access.urls')),

]

templates/adminsignup.html
<!DOCTYPE html>
{% extends 'base2.html' %}
{% block content %}
<div class="container">
    <h2>Admin Signup</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
</div>
{% endblock %}

templates/base2.html
<!DOCTYPE html>
{% load static %}



<html>
<head>
  <title>My Website</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">VEHICLE MANAGEMENT</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto  ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user_access:login' %}">Home</a>
        </li>

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_access:logout' %}">logout</a>
          </li>
        {% else %}
           <li class="nav-item">
             <a class="nav-link" href="#">about</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


{% block content %}
{% endblock %}

</body>
</html>

templates/create.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Create Vehicle</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock %}

templates/delete.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Delete Vehicle</h1>
  <p>Are you sure you want to delete the vehicle "{{ vehicle.vehicle_number }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'list' %}">Cancel</a>
  </form>
{% endblock %}

templates/detail.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Vehicle Detail</h1>
  <p><strong>Vehicle Number:</strong> {{ vehicle.vehicle_number }}</p>
  <p><strong>Vehicle Type:</strong> {{ vehicle.vehicle_type }}</p>
  <p><strong>Vehicle Model:</strong> {{ vehicle.vehicle_model }}</p>
  <p><strong>Vehicle Description:</strong> {{ vehicle.vehicle_description }}</p>
{% endblock %}

templates/home.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}

<div class="container_fluid mx-5 my-5 text-center" style="bottom:30px;">
<center>
hello
<h5><a class="btn btn-danger" aria-current="page" href="{% url 'user_access:login' %}" style="width: 150px;">LOGIN</a></h5>
<h5><a class="btn btn-danger" aria-current="page" href="{% url 'user_access:usersignup' %}" style="width: 150px;">user signup</a></h5>
<h5><a class="btn btn-danger" aria-current="page" href="{% url 'user_access:adminsignup' %}" style="width: 150px;">Admin signup</a></h5>
<h5><a class="btn btn-danger" aria-current="page" href="{% url 'user_access:superadminsign' %}" style="width: 150px;">SuperUser signup</a></h5>
        </center>
</div>
{% endblock %}

templates/list.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Vehicle List</h1>
  {% if vehicles %}
    <ul>
      {% for vehicle in vehicles %}
        <li>{{ vehicle.vehicle_number }} - {{ vehicle.vehicle_type }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No vehicles found.</p>
  {% endif %}
{% endblock %}

templates/list1.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Vehicle List For User</h1>
  {% if vehicles %}
    <ul>
      {% for vehicle in vehicles %}
        <li>{{ vehicle.vehicle_number }} - {{ vehicle.vehicle_type }}
             <a href="{% url 'user_access:detail' vehicle.pk %}">view</a>
        </li>

      {% endfor %}
    </ul>
  {% else %}
    <p>No vehicles found.</p>
  {% endif %}
{% endblock %}

templates/list3.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Vehicle List For Admin</h1>
  {% if vehicles %}
    <ul>
      {% for vehicle in vehicles %}
        <li>{{ vehicle.vehicle_number }} - {{ vehicle.vehicle_type }}
             <a href="{% url 'user_access:update' vehicle.pk %}">Update</a>
        </li>

      {% endfor %}
    </ul>
  {% else %}
    <p>No vehicles found.</p>
  {% endif %}
{% endblock %}

templates/login.html
{% extends 'base2.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

templates/profile.html
{% extends 'base2.html' %}

{% block content %}
  <h2>Vehicle Management Profile</h2>
  <div>
    <h3>User Information</h3>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
  </div>
  <div>
    <h3>Vehicle Information</h3>
    {% if user.vehicles.exists %}
      <ul>
        {% for vehicle in user.vehicles.all %}
          <li>{{ vehicle.number }} {{ vehicle.model }} {{vehicle_type}} {{ vehicle_description }})</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No vehicles found.</p>
    {% endif %}
  </div>
{% endblock %}



<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--    <title>Profile</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h2>User Profile</h2>-->
<!--    <p>Welcome, {{ user.username }}!</p>-->
<!--</body>-->
<!--</html>-->

templates/superadmin_signup.html
<!DOCTYPE html>
{% extends 'base2.html' %}
{% block content %}
<div class="container">
    <h2>Super Admin Signup</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
</div>
{% endblock %}

templates/update.html
{% extends 'base2.html' %}

{% block content %}
  <h1>Update Vehicle</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}

templates/user_signup.html
<!DOCTYPE html>
{% extends 'base2.html' %}
{% block content %}
<div class="container">
    <h2>User Signup</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit">
    </form>
</div>
{% endblock %}